version: '3'

services:
  kiritan:
    container_name: kiritan
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    stdin_open: true
    volumes:
      - ./src:/tmp
    working_dir: /tmp/NEUTRINO-Linux